### ISSUE TITLE
docker权限问题

### ISSUE THREAD

**Issue by zxl78585** [gitlab-ce-zh/gitlab-ce-zh#2]
您好，我在汉化的gitlab首选项中，设置主题的时候，总是跳转到422页面，我试了官方的gitlab，是正常的。
![1](https://user-images.githubusercontent.com/19941977/34609296-1d1ac5b6-f257-11e7-8417-e1573d29960c.png)

![1](https://user-images.githubusercontent.com/19941977/34609313-2a95e5e0-f257-11e7-97b0-84537d1a5f32.png)

**Comment by maikebing** [comment]
在  https://gitlab.com/xhang/gitlab  咨询一下。
